# Generated by Django 5.2.17 on 2026-09-07 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('CIRCLE', 'Circle'), ('POLYGON', 'Polygon'), ('RECTANGLE', 'Rectangle')], max_length=20)),
                ('geometry', models.JSONField(help_text='CIRCLE: {center: [lng, lat], radius_m: number}; POLYGON: {coordinates: [[lng, lat], ...]}; RECTANGLE: {bounds: [[sw_lng, sw_lat], [ne_lng, ne_lat]]}')),
                ('radius_m', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_on_entry', models.BooleanField(default=True)),
                ('alert_on_exit', models.BooleanField(default=True)),
                ('assign_all', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_geofences', to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ManyToManyField(blank=True, related_name='geofences', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='geofences_g_company_2877a6_idx')],
            },
        ),
    ]
