# Generated by Django 5.2.17 on 2026-09-07 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('rpm', models.FloatField(blank=True, null=True)),
                ('coolant_temperature', models.FloatField(blank=True, null=True)),
                ('engine_load', models.FloatField(blank=True, null=True)),
                ('throttle_position', models.FloatField(blank=True, null=True)),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('fuel_level', models.FloatField(blank=True, null=True)),
                ('intake_air_temperature', models.FloatField(blank=True, null=True)),
                ('engine_runtime', models.FloatField(blank=True, null=True)),
                ('odometer', models.FloatField(blank=True, null=True)),
                ('ignition', models.BooleanField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_records', to='devices.device')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='telemetry_v_vehicle_8f6aeb_idx'), models.Index(fields=['device', '-timestamp'], name='telemetry_v_device__46aa4a_idx'), models.Index(fields=['-timestamp'], name='telemetry_v_timesta_53b25d_idx')],
            },
        ),
    ]
