# Generated by Django 5.2.17 on 2026-09-07 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('imei', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('firmware_version', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='UNASSIGNED', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='companies.company')),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_device', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['serial_number'],
                'indexes': [models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx'), models.Index(fields=['company', 'status'], name='devices_dev_company_c2b2f8_idx'), models.Index(fields=['last_seen_at'], name='devices_dev_last_se_c75af6_idx')],
            },
        ),
    ]
