# Generated by Django 5.2.17 on 2026-09-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('devices', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='terminal_phone',
            field=models.CharField(blank=True, help_text='JT808 terminal phone ID (12-digit BCD)', max_length=16, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['terminal_phone'], name='devices_dev_termina_5032d0_idx'),
        ),
    ]
