# Generated by Django 5.2.17 on 2026-09-07 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HIGH_COOLANT_TEMPERATURE', 'High Coolant Temperature'), ('LOW_BATTERY', 'Low Battery'), ('HIGH_RPM', 'High RPM'), ('ENGINE_DTC', 'Engine DTC'), ('DEVICE_OFFLINE', 'Device Offline'), ('SPEED_LIMIT', 'Speed Limit')], max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle', '-created_at'], name='alerts_vehi_vehicle_d03dff_idx'), models.Index(fields=['severity', 'resolved_at'], name='alerts_vehi_severit_82fb61_idx')],
            },
        ),
    ]
