# Generated by Django 5.2.17 on 2026-09-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclealert',
            name='type',
            field=models.CharField(choices=[('HIGH_COOLANT_TEMPERATURE', 'High Coolant Temperature'), ('LOW_BATTERY', 'Low Battery'), ('HIGH_RPM', 'High RPM'), ('ENGINE_DTC', 'Engine DTC'), ('DEVICE_OFFLINE', 'Device Offline'), ('SPEED_LIMIT', 'Speed Limit'), ('GEOFENCE_ENTER', 'Geofence Enter'), ('GEOFENCE_EXIT', 'Geofence Exit')], max_length=40),
        ),
    ]
